"""
Data Models for Crypto Scanner
Defines all data structures used across the system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any


class Timeframe(Enum):
    """Supported timeframes for analysis"""
    MINUTE_15 = "15m"
    HOUR_1 = "1h"
    HOUR_4 = "4h"
    DAILY = "daily"
    
    @property
    def minutes(self) -> int:
        """Get minutes for this timeframe"""
        mapping = {
            "15m": 15,
            "1h": 60,
            "4h": 240,
            "daily": 1440
        }
        return mapping.get(self.value, 60)


class StrategyType(Enum):
    """Strategy types supported by the scanner"""
    TREND_CONTINUATION = "Trend Continuation"
    BEARISH_SHORT = "Bearish Trend Short"
    LIQUIDITY_SWEEP = "Liquidity Sweep Reversal"
    VOLATILITY_BREAKOUT = "Volatility Breakout"
    NONE = "None"


class TrendDirection(Enum):
    """Trend direction"""
    BULLISH = "Bullish"
    BEARISH = "Bearish"
    NEUTRAL = "Neutral"


class SignalDirection(Enum):
    """Signal direction"""
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


@dataclass
class OHLCV:
    """OHLCV Candle Data"""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    @property
    def body(self) -> float:
        """Candle body size"""
        return abs(self.close - self.open)
    
    @property
    def is_bullish(self) -> bool:
        """Is candle bullish"""
        return self.close > self.open
    
    @property
    def upper_wick(self) -> float:
        """Upper wick size"""
        return self.high - max(self.open, self.close)
    
    @property
    def lower_wick(self) -> float:
        """Lower wick size"""
        return min(self.open, self.close) - self.low


@dataclass
class CoinData:
    """Coin market data with indicators"""
    symbol: str
    name: str
    current_price: float
    market_cap: float
    volume_24h: float
    price_change_24h: float
    price_change_percent_24h: float
    
    # OHLCV data per timeframe
    candles: Dict[str, List[OHLCV]] = field(default_factory=dict)
    
    # Indicator values
    ema_20: Optional[float] = None
    ema_50: Optional[float] = None
    ema_100: Optional[float] = None
    ema_200: Optional[float] = None
    rsi: Optional[float] = None
    atr: Optional[float] = None
    volume_ma: Optional[float] = None
    
    # Bollinger Bands
    bb_upper: Optional[float] = None
    bb_middle: Optional[float] = None
    bb_lower: Optional[float] = None
    
    # Trend
    trend: TrendDirection = TrendDirection.NEUTRAL
    
    # Additional data
    rank: int = 0
    last_updated: datetime = field(default_factory=datetime.now)
    
    @property
    def market_cap_millions(self) -> float:
        """Market cap in millions"""
        return self.market_cap / 1_000_000
    
    @property
    def volume_24h_millions(self) -> float:
        """24h volume in millions"""
        return self.volume_24h / 1_000_000


@dataclass
class TradingSignal:
    """Trading signal generated by strategy engines"""
    # Identification
    id: str = field(default_factory=lambda: datetime.now().strftime("%Y%m%d%H%M%S%f"))
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Coin info
    symbol: str = ""
    name: str = ""
    
    # Signal details
    direction: SignalDirection = SignalDirection.NEUTRAL
    strategy_type: StrategyType = StrategyType.NONE
    timeframe: str = ""
    
    # Entry/Exit
    entry_zone_min: float = 0
    entry_zone_max: float = 0
    stop_loss: float = 0
    target_1: float = 0
    target_2: float = 0
    
    # Risk/Reward
    risk_reward: float = 0
    risk_amount: float = 0
    
    # Scoring
    confidence_score: float = 0
    score_breakdown: Dict[str, Any] = field(default_factory=dict)
    
    # Reasoning
    reasoning: str = ""
    trend_alignment: bool = False
    volume_confirmation: bool = False
    volatility_expansion: bool = False
    btc_alignment: bool = False
    liquidity_sweep: bool = False
    
    # Hybrid AI reasoning (Phase 3)
    hybrid_reasoning: str = ""
    ai_reasoning_contribution: float = 0.0
    rule_based_confidence: float = 0.0
    
    # Market context
    btc_trend: TrendDirection = TrendDirection.NEUTRAL
    current_price: float = 0
    
    # Accumulation/Breakout fields
    range_low: float = 0
    range_high: float = 0
    near_breakout: bool = False
    breakout_distance_pct: float = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "name": self.name,
            "direction": self.direction.value,
            "strategy_type": self.strategy_type.value,
            "timeframe": self.timeframe,
            "entry_zone": f"{self.entry_zone_min:.2f} - {self.entry_zone_max:.2f}",
            "stop_loss": self.stop_loss,
            "target_1": self.target_1,
            "target_2": self.target_2,
            "risk_reward": f"1:{self.risk_reward:.1f}",
            "confidence_score": self.confidence_score,
            "reasoning": self.reasoning
        }
    
    def to_alert_string(self) -> str:
        """Format as alert message"""
        direction_emoji = "🟢" if self.direction == SignalDirection.LONG else "🔴"
        strategy = self.strategy_type.value
        
        risk_level = self._get_risk_level()
        
        rr = f"1:{self.risk_reward:.1f}"
        
        message = f"""
{direction_emoji} <b>{self.direction.value} SETUP DETECTED</b>

<b>{self.symbol}</b> ({self.name})
Strategy: {strategy}
Timeframe: {self.timeframe}
Confidence: {self.confidence_score:.1f}/10

💰 <b>Entry Zone</b>
{self.entry_zone_min:.4f} - {self.entry_zone_max:.4f}

🛡️ <b>Stop Loss</b>
{self.stop_loss:.4f}

🎯 <b>Targets</b>
T1: {self.target_1:.4f}
T2: {self.target_2:.4f}

📈 <b>Risk/Reward</b>
{rr}

⚠️ <b>Risk Level</b>
{risk_level}
"""
        
        if self.range_high > 0 or self.range_low > 0:
            message += f"""
📊 <b>Trading Range</b>
Low: {self.range_low:.4f}
High: {self.range_high:.4f}
"""
        
        if self.near_breakout:
            message += f"""
🚀 <b>Near Breakout</b>
Distance: {self.breakout_distance_pct:.1f}%
"""
        
        if self.reasoning:
            message += f"""
📝 <b>Reasoning</b>
{self.reasoning[:400]}
"""
        
        return message
    
    def _get_risk_level(self) -> str:
        """Determine risk level"""
        if self.confidence_score >= 8 and self.risk_reward >= 2:
            return "🟢 LOW"
        elif self.confidence_score >= 6 and self.risk_reward >= 1.5:
            return "🟡 MEDIUM"
        else:
            return "🔴 HIGH"


@dataclass
class TradeRecord:
    """Record of executed trade for performance tracking"""
    signal_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    
    symbol: str = ""
    entry_price: float = 0
    stop_loss: float = 0
    target_1: float = 0
    target_2: float = 0
    
    actual_exit: Optional[float] = None
    actual_direction: SignalDirection = SignalDirection.NEUTRAL
    
    status: str = "OPEN"  # OPEN, CLOSED_WIN, CLOSED_LOSS
    pnl_percent: float = 0
    notes: str = ""


@dataclass
class MarketSummary:
    """Summary of market conditions"""
    btc_trend: TrendDirection = TrendDirection.NEUTRAL
    btc_price: float = 0
    btc_rsi: float = 0
    
    total_signals: int = 0
    long_signals: int = 0
    short_signals: int = 0
    
    top_coins_bullish: List[str] = field(default_factory=list)
    top_coins_bearish: List[str] = field(default_factory=list)
    
    market_regime: str = "NEUTRAL"  # BULL, BEAR, NEUTRAL, VOLATILE
    scan_duration_seconds: float = 0


class SignalResolution(Enum):
    """Signal resolution types"""
    TARGET_1_HIT = "TARGET_1_HIT"
    TARGET_2_HIT = "TARGET_2_HIT"
    STOP_LOSS_HIT = "STOP_LOSS_HIT"
    EXPIRED = "EXPIRED"


@dataclass
class SignalOutcome:
    """Outcome of a resolved trading signal for learning purposes"""
    signal_id: str = ""
    symbol: str = ""
    strategy_type: StrategyType = StrategyType.NONE
    timeframe: str = ""
    direction: SignalDirection = SignalDirection.NEUTRAL
    
    # Resolution details
    resolution: SignalResolution = SignalResolution.EXPIRED
    pnl_percent: float = 0
    duration_hours: float = 0
    
    # Prices
    entry_price: float = 0
    stop_loss: float = 0
    target_1: float = 0
    target_2: float = 0
    price_at_resolution: float = 0
    
    # Metadata
    timestamp: datetime = field(default_factory=datetime.now)
    confidence_score: float = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "strategy_type": self.strategy_type.value,
            "timeframe": self.timeframe,
            "direction": self.direction.value,
            "resolution": self.resolution.value,
            "pnl_percent": self.pnl_percent,
            "duration_hours": self.duration_hours,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "target_1": self.target_1,
            "target_2": self.target_2,
            "price_at_resolution": self.price_at_resolution,
            "timestamp": self.timestamp.isoformat(),
            "confidence_score": self.confidence_score
        }
